### ISSUE TITLE
[BUG] error in training examples/water/se_e3:failed to run cuBLAS routine: CUBLAS_STATUS_INVALID_VALUE

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#1062]
See #1061.

I can reproduce the error.

CPU works fine.

**Comment by njzjz** [comment]
CUDA 10.1 works fine. Maybe a bug in CUDA 11.3?

**Comment by njzjz** [comment]
update: it's related to memory. Reducing `sel` to a proper number can avoid the error. However, I don't find the root reason yet.

**Comment by amcadmus** [comment]
The memory consumption of se3 is much larger than se2. therefore one is recommended to use smaller rcut and sel for se3. A hybridization of se2 (standard rc) and se3 (small rc) is a good practice.

**Comment by Dankomaister** [comment]
Hi!

I'm running parallel training using DeepMD 2.0.0 on a compute node with 8x NVIDIA A100 GPUs (A100-SXM4-40GB).
These GPUs have 40GB of memory each. However, I cant seem to be able to use more than around 3GB of memory per GPU without running into the `failed to run cuBLAS routine: CUBLAS_STATUS_INVALID_VALUE` error.

For the dataset I'm using, running with a batch size of 16 works fine and shows memory utilization of around 3GB per GPU.
But increasing the batch size to 17 causes the `failed to run cuBLAS routine: CUBLAS_STATUS_INVALID_VALUE` error.
It doesn't seem reasonable that increasing the batch size from 16 to 17 would cause the memory usage to increase to more than 40 GB per GPU.

Especially since the memory usage increase with the batch size is not that big
batch size = 5   uses ~1400 MB memory per GPU
batch size = 10 uses ~1930 MB memory per GPU
batch size = 15 uses ~2950 MB memory per GPU
batch size = 16 uses ~2950 MB memory per GPU

Could this be related to something else then memory?

I attached some logfiles of the error and screenshots of the memory usage.
[batch size = 17.txt](https://github.com/deepmodeling/deepmd-kit/files/7126614/batch.size.17.txt)
[batch size = 20.txt](https://github.com/deepmodeling/deepmd-kit/files/7126616/batch.size.20.txt)

batch size = 5
<img width="559" alt="batch size = 5" src="https://user-images.githubusercontent.com/14222532/132462607-3beb2697-b9ca-4a7f-9256-cbf6c840f053.PNG">

batch size = 10
<img width="560" alt="batch size = 10" src="https://user-images.githubusercontent.com/14222532/132462609-54657722-25d9-4e31-9458-a5c72b44ac17.PNG">

batch size = 15
<img width="561" alt="batch size = 15" src="https://user-images.githubusercontent.com/14222532/132462612-add23455-bd31-4b03-90a1-71515bfcc619.PNG">

batch size = 16
<img width="559" alt="batch size = 16" src="https://user-images.githubusercontent.com/14222532/132462604-e4de0615-b31e-4a95-897a-d2ac3ea0613d.PNG">

/Daniel

**Comment by Dankomaister** [comment]
Hi,

Is this issue now solved with the new version (v2.0.2) of deepmd-kit?

/Daniel

**Comment by njzjz** [comment]
Hi @Dankomaister, you can try pip packages instead by following https://docs.deepmodeling.org/projects/deepmd/en/v2.0.2/install/install-from-source.html#install-the-python-interface

**Comment by njzjz** [comment]
Note: this may be a bug of cuBLAS, which we cannot fix by ourselves.
See https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cublas-11.4.0

**Comment by njzjz** [comment]
> OK, maybe I will try that! Have you tested and confirmed that this problem is solved when using CUDA 11.2 together with DeePMD 2.0.2 ?

As reported by https://github.com/tensorflow/tensorflow/issues/54463#issuecomment-1063739811, CUDA 11.2 also has this bug.

Next time when I build TensorFlow, I will bump the CUDA version to 11.4.

**Comment by njzjz** [comment]
The next release will bump CUDA version from 11.3 to 11.6.

**Comment by njzjz** [comment]
The installer [v2.1.1](https://github.com/deepmodeling/deepmd-kit/releases/tag/v2.1.1) with CUDA 11.6 has been released.
