### ISSUE TITLE
the problem when installing the C++ interface

### ISSUE THREAD

**Issue by codecreativein** [deepmodeling/deepmd-kit#1408]
When installing the tensorflow_cc, I met the error:
![image](https://user-images.githubusercontent.com/65108372/148880542-5824ab0e-aaa1-4548-809f-e2d427be4f2c.png)
I felt very confused because actually there is the libcudart.so.11.2.74 in '/usr/local/cuda-11.2/targets/x86_64-linux/lib', however the soname of the libcudart.so.11.2.74 is libcudart.so.11.0. And the soname of libcudart.so.11.4.* is libcudart.so.11.0 too

**Comment by njzjz** [comment]
If you are building tensorflow 2.3, to my knowledge, it does not support CUDA 11.2. If not, you may seek help from TensorFlow's repo: https://github.com/tensorflow/tensorflow/issues

**Comment by codecreativein** [comment]
I would go to the Tensorflow's repo to look for the answer, thanks a lot .

**Comment by njzjz** [comment]
I think this error has been fixed by https://github.com/tensorflow/tensorflow/pull/43716 (released in TF 2.4).
